package $

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

{package}.modules.controller;

/**
 * 页面controller, 按需改名 generated by hik-ga-archetype-webapp
 *
 * @author
 */
@Controller
public class WebController {

  @RequestMapping(value = "/", method = {RequestMethod.GET})
  public String index() {
    return "index";
  }

  @RequestMapping(value = "/getString", method = {RequestMethod.GET})
  @ResponseBody
  public String getString() {
    return "success";
  }

}