<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- meta获取csrf token -->
	<meta name="_csrf" content="${(_csrf.token)!}" />
	<meta name="_csrf_header" content="${(_csrf.headerName)!}" />
	<title>index</title>
</head>

<body>
<p>This is index generated by scaffold-archetype</p>
<a href="/test">test</a>
</body>

</html>
